### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Goalkov** [NewtheBuilder/Announce#1]
Add the /buyannounce command, this is a command ONLY for players, with it, players will be able to buy and write an announcement in the chat to all players, UI form will buy and write an announcement in the chat! Dependencies: BedrockEconomy, EconomyApi 2 DEPENDENCIES to be! Also, after sending the announcement, their in-game nickname will be indicated in the chat, for example "[player - announce] [Steve] > text.BUT so that the admin ads / announce do not have a nickname visible in the chat who wrote the ad! 

We are waiting for these updates!

**Comment by Dumont-Julien** [comment]
Okey, I take notes

**Comment by Goalkov** [comment]
/buyan then a user interface form opens, there will be a price, it will first load, then a line will open where you need to write an announcement in the chat for all players!

**Comment by Dumont-Julien** [comment]
understood

**Comment by Dumont-Julien** [comment]
can i have a commentaire in my others plugins please ?

Le ven. 25 févr. 2022 à 23:27, Julien Dumont ***@***.***> a
écrit :

**Comment by Dumont-Julien** [comment]
I have finish your modification

Le ven. 25 févr. 2022 à 23:47, Julien Dumont ***@***.***> a
écrit :

**Comment by Dumont-Julien** [comment]
Hello i have question, when my plugin have  reponse  please ?


Le sam. 26 févr. 2022 à 14:10, Julien Dumont ***@***.***> a
écrit :
